# Generated by Django 5.2.4 on 2025-07-11 07:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloglike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Blog post content with rich text formatting', verbose_name='Text'),
        ),
    ]
